### ISSUE TITLE
ENHANCEMENT - Allow the closing / flipping of a sizing even without all members having voted

### ISSUE THREAD

**Issue by JosephCDonaldson** [Toxantron/scrumonline#134]
A common issue I have noticed is that during a sizing session, a person will have walked away from their computer for a moment during sizing.  This results in us poking/prodding folks "Hey, Bob - we need a size?  Bob?  Bob - we are going to kick you?" and its just a bit awkward.

It would be nice if the leader of the sizing had a button that was basically a "Close sizing, any members not having voted should place a vote with [-1] or [0] or [N/A]" and flip the cards.

This is an enhancement, not a bug, since the workaround we have currently is to kick members and ask them to join when they get back to their machine.  This would be a really nice to have feature.

**Comment by Toxantron** [comment]
Makes sense, as you can probably tell from the other activity on this repository, I barely have time for this project since my company also went open source with our project [MORYX](/PHOENIXCONTACT).

I am happy to look over a PR, that does not add another redundant card set, if you are willing to work on that. Otherwise I am on vacation towards the end of September and I hope I can cut out a few hours to get this back on track. In that case I will definitely include your suggestion. In the meantime stick with the workaround, stay home and stay safe. :-)

**Comment by Toxantron** [comment]
Done and deployed, let me know if that helps.

**Comment by JosephCDonaldson** [comment]
It does.  Thank you very much for your help.
