### ISSUE TITLE
Display private repos

### ISSUE THREAD

**Issue by Daiben** [Toxantron/scrumonline#27]
Is it possible to watch the issues from private repo's?

**Comment by Toxantron** [comment]
@Daiben not yet, but I could extend the [Github Plugin](https://github.com/Toxantron/scrumonline/blob/master/src/js/plugins.js#L69) to include [Github OAuth](https://developer.github.com/v3/oauth/) authorization.

It might take a while to read into it and implement it. Just from a quick browse it should be possible, but a question remains: *To access private repos or at least their issues, users will have to grant "me" permission to do so. Since I do not have a user model and do not plan on implementing it, as long as I can not guarantuee the safety of that data. Therefor users either would have to go through the process over and over* **OR** *I could display the token so they can store it somewhere to use in the next session.*

What would you prefer?

**Comment by Daiben** [comment]
@Toxantron I can help you maybe

https://developer.github.com/v3/issues/#list-issues-for-a-repository

https://developer.github.com/v3/#basic-authentication

Basic authentication is fine for me.

**Comment by Toxantron** [comment]
Thanks for the links. The first one I use already and the second I saw when looking up the API. 

I wasn't sure if users are comfortable entering their Github password and OAuth is the preferred way. Never the less let's start with Basic and we can add OAuth later.

**Comment by Daiben** [comment]
Great 👍  I dont mind basic authentication.

**Comment by Toxantron** [comment]
Done. Could you take it for a spin, @Daiben and give me feedback?

**Comment by Toxantron** [comment]
Make sure to clear your cache of [scrumpoker.online](http://www.scrumpoker.online/#/) first.

**Comment by Daiben** [comment]
Great :) thanks 👍

**Comment by Toxantron** [comment]
You are welcome. Closed?

**Comment by Daiben** [comment]
Review #28 please aftewards you can close it :)

**Comment by Toxantron** [comment]
Merged and made "pretty". ;-)
